version: "3"
services:
  wk-redis:
    image: redis:latest
    restart: always
    networks:
      - ${NETWORKS}
  wk-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: baenam
      POSTGRES_PASSWORD: bnchs1122
      POSTGRES_DB: outline
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - ${NETWORKS}
  wk-minio:
    image: minio/minio:latest
    volumes:
      - ./data/minio_root:/minio_root:z
      - ./data/certs:/root/.minio/certs:z
    command: "minio server /minio_root"
    env_file:
      - ./env.minio
    restart: always
    networks:
      - ${NETWORKS}
  wk-createbuckets:
    image: minio/mc
    depends_on:
      - wk-minio
    env_file:
      - ./env.minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://wk-minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb minio/outline-bucket;
      /usr/bin/mc policy set download minio/outline-bucket;
      exit 0;
      "
    networks:
      - ${NETWORKS}
  wk-outline:
    image: outlinewiki/outline:0.63.0
    command: sh -c "yarn sequelize:migrate --env production-ssl-disabled && yarn start"
    environment:
      - DATABASE_URL=postgres://baenam:bnchs1122@wk-postgres:5432/outline
      - DATABASE_URL_TEST=postgres://baenam:bnchs1122@wk-postgres:5432/outline-test
      - REDIS_URL=redis://wk-redis:6379
      - AWS_S3_UPLOAD_BUCKET_NAME=outline-bucket
    env_file:
      - ./env.outline
      - ./env.oidc
    restart: always
    depends_on:
      - wk-postgres
      - wk-redis
      - wk-minio
    networks:
      - ${NETWORKS}
  wk-oidc-server:
    image: vicalloy/oidc-server
    volumes:
      - ./config/uc/fixtures:/app/oidc_server/fixtures:z
      - ./data/uc/db:/app/db:z
      - ./data/uc/static_root:/app/static_root:z
    restart: always
    env_file:
      - ./env.oidc-server
    networks:
      - ${NETWORKS}
  wk-nginx:
    image: nginx
    ports:
      - ${HTTP_IP}:${HTTP_PORT_IP}:80
    volumes:
      - ./config/nginx/:/etc/nginx/conf.d/:ro
      - ./data/uc/static_root:/uc/static_root:ro
    restart: always
    depends_on:
      - wk-minio
      - wk-outline
      - wk-oidc-server
    networks:
      - ${NETWORKS}
networks:
  ${NETWORKS}:
    external: ${NETWORKS_EXTERNAL}
